name: Build and Deploy to Hugo Static Site

on:
  push:
    branches: [ "master" ]

env:
  CLOUDFRONT_DISTRIBUTION_ID: E2CP33IKQAMIK6
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.110.0'
        # extended: true

    - name: Build
      run: hugo --minify  # Include any other flags you need here

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: af-south-1

    - name: Copy files to S3
      run: aws s3 sync ./public/ s3://adrianvdh.com  # Set your bucket name here

    - name: Invalidate CloudFront distribution
      run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
